package edu.unlpam.vet.ponzonosos.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANIMAL".
*/
public class AnimalDao extends AbstractDao<Animal, Long> {

    public static final String TABLENAME = "ANIMAL";

    /**
     * Properties of entity Animal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "nombre", false, "NOMBRE");
        public final static Property NombreSecundario = new Property(2, String.class, "nombreSecundario", false, "NOMBRE_SECUNDARIO");
        public final static Property NombreC = new Property(3, String.class, "nombreC", false, "NOMBRE_C");
        public final static Property Tamano = new Property(4, String.class, "tamano", false, "TAMANO");
        public final static Property Agresividad = new Property(5, int.class, "agresividad", false, "AGRESIVIDAD");
        public final static Property Tipo = new Property(6, String.class, "tipo", false, "TIPO");
        public final static Property EfectoPicadura = new Property(7, String.class, "efectoPicadura", false, "EFECTO_PICADURA");
        public final static Property Antidoto = new Property(8, String.class, "antidoto", false, "ANTIDOTO");
        public final static Property Lugar_encuentro = new Property(9, String.class, "lugar_encuentro", false, "LUGAR_ENCUENTRO");
        public final static Property Accion_picadura = new Property(10, String.class, "accion_picadura", false, "ACCION_PICADURA");
        public final static Property Confusion = new Property(11, String.class, "confusion", false, "CONFUSION");
        public final static Property Descripcion = new Property(12, String.class, "descripcion", false, "DESCRIPCION");
    }

    private DaoSession daoSession;


    public AnimalDao(DaoConfig config) {
        super(config);
    }
    
    public AnimalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANIMAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"NOMBRE\" TEXT," + // 1: nombre
                "\"NOMBRE_SECUNDARIO\" TEXT," + // 2: nombreSecundario
                "\"NOMBRE_C\" TEXT," + // 3: nombreC
                "\"TAMANO\" TEXT," + // 4: tamano
                "\"AGRESIVIDAD\" INTEGER NOT NULL ," + // 5: agresividad
                "\"TIPO\" TEXT," + // 6: tipo
                "\"EFECTO_PICADURA\" TEXT," + // 7: efectoPicadura
                "\"ANTIDOTO\" TEXT," + // 8: antidoto
                "\"LUGAR_ENCUENTRO\" TEXT," + // 9: lugar_encuentro
                "\"ACCION_PICADURA\" TEXT," + // 10: accion_picadura
                "\"CONFUSION\" TEXT," + // 11: confusion
                "\"DESCRIPCION\" TEXT);"); // 12: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANIMAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Animal entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String nombreSecundario = entity.getNombreSecundario();
        if (nombreSecundario != null) {
            stmt.bindString(3, nombreSecundario);
        }
 
        String nombreC = entity.getNombreC();
        if (nombreC != null) {
            stmt.bindString(4, nombreC);
        }
 
        String tamano = entity.getTamano();
        if (tamano != null) {
            stmt.bindString(5, tamano);
        }
        stmt.bindLong(6, entity.getAgresividad());
 
        String tipo = entity.getTipo();
        if (tipo != null) {
            stmt.bindString(7, tipo);
        }
 
        String efectoPicadura = entity.getEfectoPicadura();
        if (efectoPicadura != null) {
            stmt.bindString(8, efectoPicadura);
        }
 
        String antidoto = entity.getAntidoto();
        if (antidoto != null) {
            stmt.bindString(9, antidoto);
        }
 
        String lugar_encuentro = entity.getLugar_encuentro();
        if (lugar_encuentro != null) {
            stmt.bindString(10, lugar_encuentro);
        }
 
        String accion_picadura = entity.getAccion_picadura();
        if (accion_picadura != null) {
            stmt.bindString(11, accion_picadura);
        }
 
        String confusion = entity.getConfusion();
        if (confusion != null) {
            stmt.bindString(12, confusion);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(13, descripcion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Animal entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String nombre = entity.getNombre();
        if (nombre != null) {
            stmt.bindString(2, nombre);
        }
 
        String nombreSecundario = entity.getNombreSecundario();
        if (nombreSecundario != null) {
            stmt.bindString(3, nombreSecundario);
        }
 
        String nombreC = entity.getNombreC();
        if (nombreC != null) {
            stmt.bindString(4, nombreC);
        }
 
        String tamano = entity.getTamano();
        if (tamano != null) {
            stmt.bindString(5, tamano);
        }
        stmt.bindLong(6, entity.getAgresividad());
 
        String tipo = entity.getTipo();
        if (tipo != null) {
            stmt.bindString(7, tipo);
        }
 
        String efectoPicadura = entity.getEfectoPicadura();
        if (efectoPicadura != null) {
            stmt.bindString(8, efectoPicadura);
        }
 
        String antidoto = entity.getAntidoto();
        if (antidoto != null) {
            stmt.bindString(9, antidoto);
        }
 
        String lugar_encuentro = entity.getLugar_encuentro();
        if (lugar_encuentro != null) {
            stmt.bindString(10, lugar_encuentro);
        }
 
        String accion_picadura = entity.getAccion_picadura();
        if (accion_picadura != null) {
            stmt.bindString(11, accion_picadura);
        }
 
        String confusion = entity.getConfusion();
        if (confusion != null) {
            stmt.bindString(12, confusion);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(13, descripcion);
        }
    }

    @Override
    protected final void attachEntity(Animal entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Animal readEntity(Cursor cursor, int offset) {
        Animal entity = new Animal( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nombreSecundario
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // nombreC
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tamano
            cursor.getInt(offset + 5), // agresividad
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tipo
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // efectoPicadura
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // antidoto
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // lugar_encuentro
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // accion_picadura
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // confusion
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // descripcion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Animal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNombreSecundario(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNombreC(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTamano(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAgresividad(cursor.getInt(offset + 5));
        entity.setTipo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEfectoPicadura(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAntidoto(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLugar_encuentro(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAccion_picadura(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setConfusion(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDescripcion(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Animal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Animal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Animal entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
