package edu.unlpam.vet.ponzonosos.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import edu.unlpam.vet.ponzonosos.model.Animal;
import edu.unlpam.vet.ponzonosos.model.Imagen;

import edu.unlpam.vet.ponzonosos.model.AnimalDao;
import edu.unlpam.vet.ponzonosos.model.ImagenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig animalDaoConfig;
    private final DaoConfig imagenDaoConfig;

    private final AnimalDao animalDao;
    private final ImagenDao imagenDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        imagenDaoConfig = daoConfigMap.get(ImagenDao.class).clone();
        imagenDaoConfig.initIdentityScope(type);

        animalDao = new AnimalDao(animalDaoConfig, this);
        imagenDao = new ImagenDao(imagenDaoConfig, this);

        registerDao(Animal.class, animalDao);
        registerDao(Imagen.class, imagenDao);
    }
    
    public void clear() {
        animalDaoConfig.clearIdentityScope();
        imagenDaoConfig.clearIdentityScope();
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

    public ImagenDao getImagenDao() {
        return imagenDao;
    }

}
