package edu.unlpam.vet.ponzonosos.model;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGEN".
*/
public class ImagenDao extends AbstractDao<Imagen, Long> {

    public static final String TABLENAME = "IMAGEN";

    /**
     * Properties of entity Imagen.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Img = new Property(1, String.class, "img", false, "IMG");
        public final static Property Principal = new Property(2, int.class, "principal", false, "PRINCIPAL");
        public final static Property Descargada = new Property(3, boolean.class, "descargada", false, "DESCARGADA");
        public final static Property Id_animal = new Property(4, Long.class, "id_animal", false, "ID_ANIMAL");
    }

    private Query<Imagen> animal_ImagenQuery;

    public ImagenDao(DaoConfig config) {
        super(config);
    }
    
    public ImagenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGEN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"IMG\" TEXT," + // 1: img
                "\"PRINCIPAL\" INTEGER NOT NULL ," + // 2: principal
                "\"DESCARGADA\" INTEGER NOT NULL ," + // 3: descargada
                "\"ID_ANIMAL\" INTEGER);"); // 4: id_animal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Imagen entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
        stmt.bindLong(3, entity.getPrincipal());
        stmt.bindLong(4, entity.getDescargada() ? 1L: 0L);
 
        Long id_animal = entity.getId_animal();
        if (id_animal != null) {
            stmt.bindLong(5, id_animal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Imagen entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(2, img);
        }
        stmt.bindLong(3, entity.getPrincipal());
        stmt.bindLong(4, entity.getDescargada() ? 1L: 0L);
 
        Long id_animal = entity.getId_animal();
        if (id_animal != null) {
            stmt.bindLong(5, id_animal);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Imagen readEntity(Cursor cursor, int offset) {
        Imagen entity = new Imagen( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // img
            cursor.getInt(offset + 2), // principal
            cursor.getShort(offset + 3) != 0, // descargada
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // id_animal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Imagen entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImg(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrincipal(cursor.getInt(offset + 2));
        entity.setDescargada(cursor.getShort(offset + 3) != 0);
        entity.setId_animal(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Imagen entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Imagen entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Imagen entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "imagen" to-many relationship of Animal. */
    public List<Imagen> _queryAnimal_Imagen(Long id_animal) {
        synchronized (this) {
            if (animal_ImagenQuery == null) {
                QueryBuilder<Imagen> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id_animal.eq(null));
                animal_ImagenQuery = queryBuilder.build();
            }
        }
        Query<Imagen> query = animal_ImagenQuery.forCurrentThread();
        query.setParameter(0, id_animal);
        return query.list();
    }

}
